from collections.abc import Iterator

class KeywordTree:
    def __init__(self, case_insensitive: bool = False) -> None: ...
    def add(self, keyword: str) -> None: ...
    def finalize(self) -> None: ...
    def search_all(self, text: str) -> Iterator[tuple[str, int]]: ...
